main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('sekolah/', views.sekolah, name='sekolah'),
    path('games/', views.games, name='games'),
    path('story1/', views.story1, name="story1"),
    path('watchlist/', views.watchlist, name='watchlist'),
    path('matakuliah/', views.matakuliah, name='matakuliah'),
    path('forms/', views.isianMatkul, name='forms'),
    path('kegiatan/', views.kegiatan, name='kegiatan'),
    path('isian-kegiatan/', views.register, name='isian-kegiatan')
]

project_name/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('accordion', views.accordion ,name='accordion')

]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.fungsi_halaman, name="halaman"),
    path('data/', views.fungsi_search, name="search"),
]

story9/urls.py
from django.urls import path
from .views import registerPage, loginPage, logoutPage


app_name = 'story9'

urlpatterns = [
    path('login/', loginPage, name="login"),
    path('register/', registerPage, name="register"),
    path('logout/', logoutPage, name='logout')
]

main/models.py
from django.db import models

# Create your models here.
class Matkul(models.Model):
    namaMatkul = models.CharField(max_length=50, null=True)
    dosenMatkul = models.CharField(max_length=50, null=True)
    sksMatkul = models.CharField(max_length=3, null=True)
    deskripsiMatkul = models.CharField(max_length=300, null=True)
    semesterMatkul = models.CharField(max_length=20, null=True)
    ruangMatkul = models.CharField(max_length=50, null=True)

class Kegiatan(models.Model):
    acara = models.CharField(max_length=50)

    def __str__(self):
        return self.acara

class Partisipan(models.Model):
    objek = models.CharField(max_length=50)
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)

    def __str__(self):
        return self.objek

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms
from .models import Matkul

class Isian(forms.ModelForm):
    class Meta:
        model = Matkul
        fields = [
            'namaMatkul',
            'dosenMatkul',
            'sksMatkul',
            'deskripsiMatkul',
            'semesterMatkul',
            'ruangMatkul'
        ]

        nama_attrs = {
            'type' : 'text',
            'placeholder' : 'Nama Mata Kuliah'
        }

        dosen_attrs = {
            'type' : 'text',
            'placeholder' : 'Nama Dosen Pengajar'
        }

        sks_attrs = {
            'type' : 'text',
            'placeholder' : 'Jumlah SKS'
        }

        deskripsi_attrs = {
            'type' : 'text',
            'placeholder' : 'Deskripsi'
        }

        semester_attrs = {
            'type' : 'text',
            'placeholder' : 'Semester'
        }

        ruang_attrs = {
            'type' : 'text',
            'placeholder' : 'Ruang'
        }

        namaMatkul = forms.CharField(label='', max_length=50, required=True, widget=forms.TextInput(attrs=nama_attrs))
        dosenMatkul = forms.CharField(label='', max_length=50, required=True, widget=forms.TextInput(attrs=dosen_attrs))
        sksMatkul = forms.CharField(max_length=3, label='', required=True, widget=forms.TextInput(attrs=sks_attrs))
        deskripsiMatkul = forms.CharField(label='', max_length=300, required=True, widget=forms.TextInput(attrs=deskripsi_attrs))
        semesterMatkul = forms.CharField(label='', max_length=50, required=True, widget=forms.TextInput(attrs=semester_attrs))
        ruangMatkul = forms.CharField(label='', max_length=50, required=True, widget=forms.TextInput(attrs=ruang_attrs))

story9/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'password1',
            'password2',
        ]

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import Matkul, Kegiatan, Partisipan
from .forms import Isian

def profile(request):
    return render(request, 'main/profile.html')

def sekolah(request):
    return render(request, 'main/sekolah.html')

def games(request):
    return render(request, 'main/games.html')

def story1(request):
    return render(request, 'main/story1.html')

def watchlist(request):
    return render(request, 'main/watchlist.html')

def matakuliah(request):
    matakuliah = Matkul.objects.all()
    return render(request, 'main/matakuliah.html', {"matakuliah" : matakuliah})

def isianMatkul(request):
    form = Isian()

    if request.method == 'POST':
        form = Isian(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/matakuliah')

    return render(request, 'main/forms.html', {'form':form})

def kegiatan(request):
    kegiatan_1 = Partisipan.objects.filter(kegiatan__name="Kegiatan 1")
    kegiatan_2 = Partisipan.objects.filter(kegiatan__name="Kegiatan 2")
    kegiatan_3 = Partisipan.objects.filter(kegiatan__name="Kegiatan 3")
    context = {'activity_1': activity_1, 'activity_2': activity_2, 'activity_3': activity_3,}
    return render(request, 'story4/activity.html', context)


def register(request):
    return render(request, 'main/isian-kegiatan.html')

    

story7/views.py
from django.shortcuts import render

# Create your views here.

def accordion(request):
    return render(request, 'story7/accordion.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import json
import requests

# Create your views here.

def fungsi_halaman(request):
    return render(request, 'story8/story8.html')

def fungsi_search(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    result = requests.get(url)
    print(result)
    data = json.loads(result.content)
    return JsonResponse(data, safe=False)

story9/views.py
from django.shortcuts import render, redirect
from .forms import CreateUserForm
from django.contrib.auth import login, logout, authenticate

# Create your views here.

def registerPage(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')

    context = {'form':form}
    return render(request, 'story9/register.html', context)

def loginPage(request):
    user = request.user
    if user.is_authenticated:
        return redirect('/')
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
            
    return render(request, 'story9/login.html')

def logoutPage(request):
    logout(request)
    return redirect('/')

main/templates/main/forms.html
{% extends 'base.html'%}
{% load static %}

{%block content%}
<form action="" method="POST">
    {% csrf_token %}
    <table>
      <tr>
        <td><p>Nama Mata Kuliah</p></td>
        <td><p><input type="text" name="namaMatkul" placeholder="Nama mata kuliah" class></p></td>
      </tr>
      <tr>
        <td><p>Nama Dosen/Pengajar</p></td>
        <td><p><input type="text" name="dosenMatkul" placeholder="Nama dosen/pengajar" class></p></td>
      </tr>
      <tr>
        <td><p>Jumlah SKS</p></td>
        <td><p><input type="text" name="sksMatkul" placeholder="Jumlah SKS" class></p></td>
      </tr>
      <tr>
        <td><p>Deskripsi</p></td>
        <td><p><input type="text" name="deskripsiMatkul" placeholder="Deskripsi" class></p></td>
      </tr>
      <tr>
        <td><p>Semester</p></td>
        <td><p><input type="text" name="semesterMatkul" placeholder="Semester" class></p></td>
      </tr>
      <tr>
        <td><p>Ruang</p></td>
        <td><p><input type="text" name="ruangMatkul" placeholder="Ruang" class></p></td>
      </tr>
    </table>
   
    <input type="submit" value="Submit">
</form>
{%endblock%}

main/templates/main/games.html
{% extends 'base.html'%}
{% load static %}

{%block content%}
<div class="text-box">
    <h1 class="text-box" style="display: block;">Played Games</h1>
    <ul>
      <li><h2 style="display: block;">Dota 2</h2></li>
      <li><h2 style="display: block;">CSGO</h2></li>
      <li><h2 style="display: block;">Valorant</h2></li>
    </ul>
</div>
{%endblock%}
        

main/templates/main/home.html
{% extends 'base.html'%}
{% load static %}

{%block content%}
<p>Selamat Datang</p>
{%endblock%}

main/templates/main/isian-kegiatan.html
{% extends 'base.html'%}
{% load static %}

{%block content%}
<form action="" method="POST">
    {% csrf_token %}
    <table>
      <tr>
        <td><p>Nama</p></td>
        <td><p><input type="text" name="namaMatkul" placeholder="Nama mata kuliah" class></p></td>
      </tr>
      <tr>
        <td><p>Kegiatan</p></td>
        <td><p><input type="text" name="dosenMatkul" placeholder="Nama dosen/pengajar" class></p></td>
      </tr>
    </table>
   
    <input type="submit" value="Submit">
</form>
{%endblock%}

main/templates/main/kegiatan.html
{% extends 'base.html'%}
{% load static %}

{%block content%}
<p>Kegiatan</p>
{%endblock%}

main/templates/main/matakuliah.html
{% extends 'base.html'%}
{% load static %}

{%block content%}
<div class="text-box">
    <h2>Mata Kuliah</h2>
    <table>
        <tr>
            <th>Nama Mata Kuliah</th>
            <th>Nama Dosen Pengampu</th>
            <th>SKS</th>
            <th>Deskripsi</th>
            <th>Semester</th>
            <th>Ruang</th>
        </tr>
        <tr>
        {% for matkul in matakuliah %}
        <td>{{ matkul.namaMatkul }}</td>
        <td>{{ matkul.dosenMatkul }}</td>
        <td>{{ matkul.sksMatkul }}</td>
        <td>{{ matkul.deskripsiMatkul }}</td>
        <td>{{ matkul.semesterMatkul }}</td>
        <td>{{ matkul.ruangMatkul }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{%endblock%}

main/templates/main/profile.html
{% extends 'base.html'%}
{% load static %}

{%block content%}
<div class="text-box">
    <h1 class="text-box" style="display: block;">Data diri</h1>
    <p style="display: block; margin: 20px;">Nama     : Hernowo Ari Sutanto <br></p>
    <p style="display: block; margin: 20px;">NPM      : 1906400274 <br></p>
    <p style="display: block; margin: 20px;">Jurusan  : Ilmu Komputer <br></p>
    <p style="display: block; margin: 20px;">Fakultas : Ilmu Komputer <br></p>
    <p style="display: block; margin: 20px;">Angkatan : 2019 <br></p>
</div>
{%endblock%}
        

main/templates/main/sekolah.html
{% extends 'base.html'%}
{% load static %}

{%block content%}
<div class="text-box">
    <h1 class="text-box" style="display: block;">Riwayat pendidikan</h1>
    <h2 style="display: block; margin-top: 20px;">SD Negeri 20 Mekarjaya</h2>
    <p style="display: block; margin-bottom: 20px;">2007 - 2013</p>
    <h2 style="display: block; margin-top: 20px;">SMP Negeri 4 Depok</h2>    
    <p style="display: block; margin-bottom: 20px;">2013 - 2016</p>
    <h2 style="display: block; margin-top: 20px;">SMA Negeri 1 Depok</h2>
    <p style="display: block; margin-bottom: 20px;">2016 - 2019</p>
</div>
{%endblock%}
        

main/templates/main/story1.html
{% extends 'base.html'%}
{% load static %}

{% block content %}
<h1>Hello...</h1>
<left><img src="{% static 'images/fotodiri.jpg'%}" width="250" height="300"></left>
<h2>Kenalan Yukk</h2>
<p>Halo, nama saya Hernowo Ari Sutanto, biasa dipanggil Hernowo, Nowo, atau Owo.<br>
Saya saat ini adalah seorang mahasiswa jurusan Ilmu Komputer di Universitas Indonesia.<br>
Hal yang biasa saya lakukan diwaktu luang adalah bermain video game.</p>
<h2>Data Diri Singkat</h2>
<ul>
    <li>Nama     :Hernowo Ari Sutanto</li>
    <li>NPM      :1906400274</li>
    <li>Angkatan :Maung (2019)</li>
</ul>
<h2>Riwayat Pendidikan</h2>
<ul>
    <li>SD Negeri 20 Mekarjaya</li>
    <li>SMP Negeri 4 Depok</li>
    <li>SMA Negeri 1 Depok</li>
</ul>
<h2>Kontak</h2>
<ul>
    <li><a href="https://www.instagram.com/hernowo.arisutanto/" target="_blank">
    <span><img src="{% static 'images/iglogo.png'%}" width="50"></span></a></li>
    <li><a href="https://steamcommunity.com/id/BadBadtzMARU" target="_blank">
    <span><img src="{% static 'images/steamlogo.png'%}" width="50"></span></a></li>
</ul> 
{% endblock %}

main/templates/main/watchlist.html
{% extends 'base.html'%}
{% load static %}

{% block content %}
<div class="text-box">
    <h1 class="text-box" style="display: block;">Film/Series yang mau di tonton</h1>
    <ul>
      <li><h3 style="display: block;">Dark</h3>
        <img src="{% static 'images\dark.jpg' %}" style="height: 280px; width: 250px; margin-bottom: 20px;"></li>
      <li><h3 style="display: block;">Blood of Zeus</h3>
        <img src="{% static 'images\Blood-of-Zeus.jpg' %}" style="height: 280px; width: 300px; margin-bottom: 20px;"></li>
      <li><h3 style="display: block;">Dragon Prince</h3>
        <img src="{% static 'images\TheDragonPrince.jpg' %}" style="height: 280px; width: 250px; margin-bottom: 20px;"></li>
    </ul>
</div>
{% endblock %}

story7/templates/story7/accordion.html
{% extends 'base.html' %}

        {% block head %}
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script>
            $(document).ready(function(){
                $(".accordion-header").click(function(){
                    if ($(this).hasClass("active")){
                        $(this).removeClass("active");
                    }
                    else {
                    $(".accordion-header").removeClass("active");
                    $(this).addClass("active");
                    }
                });
            });

            function moveUp(event){
                event.preventDefault();
                event.stopPropagation();
                $(event.currentTarget.parentNode.parentNode.previousElementSibling).insertAfter($(event.currentTarget.parentNode.parentNode))
            }

            function moveDown(event){
                event.preventDefault();
                event.stopPropagation();
                $(event.currentTarget.parentNode.parentNode).insertAfter($(event.currentTarget.parentNode.parentNode.nextElementSibling))
            }

        </script>
        <style>
            .wrapper{
                padding: 20px;
            }

            .wrapper .accordion-wrapper .accordion-header{
                width: 100%;
                background: #ffffff;
                border-bottom: 2px solid black;
                font-size: 25px;
                padding: 5px;
                font-weight: bold;
            }

            button {
                border: 1px solid black;
                background: none;
                padding: 5px;
                font-size: 17px;
                float: right;
                margin-right: 5px;
            
            }

            button:active {
                background: #7d7d7d;
            }

            .wrapper .accordion-wrapper .accordion-header:hover{
                color: #7d7d7d;
            }

            .wrapper .accordion-wrapper .accordion-body{
                width: 100%;
                height: 0px;
                transition: all 0.5s ease;
                overflow: hidden;
                margin: 5px;
            }

            .wrapper .accordion-wrapper .accordion-body p{
                padding: 15px;
                font-size: 20px;
                line-height: 22px;
            }

            .wrapper .accordion-wrapper .accordion-header.active{
                color: #7d7d7d;
            }

            .wrapper .accordion-wrapper .accordion-header.active + .accordion-body{
                height: 150px;
            }


        </style>
        {% endblock %}
        {% block content %}
        <div class="wrapper">
            <div class="accordion-wrapper">
                <div class='accordion-header'>
                    Aktivitas saat ini
                    <button onclick="moveUp(event)">UP</button>
                    <button onclick="moveDown(event)">DOWN</button>
                </div>
                <div class="accordion-body">
                    <p>Mahasiswa jurusan Ilmu Komputer di Universitas Indonesia</p>
                </div>
            </div>
            <div class="accordion-wrapper">
                <div class='accordion-header'>
                    Pengalaman organisasi
                    <button onclick="moveUp(event)">UP</button>
                    <button onclick="moveDown(event)">DOWN</button>
                </div>
                <div class="accordion-body">
                    <p>-</p>
                </div>
            </div>
            <div class="accordion-wrapper">
                <div class='accordion-header'>
                    Prestasi
                    <button onclick="moveUp(event)">UP</button>
                    <button onclick="moveDown(event)">DOWN</button>
                </div>
                <div class="accordion-body">
                    <p>-</p>
                </div>
            </div>
            <div class="accordion-wrapper">
                <div class='accordion-header'>
                    Hobi
                    <button onclick="moveUp(event)">UP</button>
                    <button onclick="moveDown(event)">DOWN</button>
                </div>
                <div class="accordion-body">
                    <p>Bermain game dan tidur</p>
                </div>
            </div>
        </div>
        {% endblock %}

story9/templates/story9/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SEKELE - Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>

    <style>
        *{
            margin: 0%;
            padding:0%;
            font-family: 'Poppins';
            text-decoration: none;
        }

        .container{
            background-color: #ccbcac;
            width: 400px;
            justify-content: center;
            margin-top : 5%;
            margin-bottom: 5%;
            border-radius: 23px;
            padding: 2%;
        }

        h1{
            text-align: center;
            font-family: Poppins;
            font-style: normal;
            font-weight: bold;
            font-size: 50px;
            line-height: 96px;
            /* identical to box height */

            color: #222222;
        }

        input[type="text"], input[type="password"]
        {
            width: 80%;
            margin: 5% 10%;
            padding-top: 5%;
            padding-bottom: 5%;
            border-radius: 10px;
            border-style: none;
            outline: none;
            text-align: center;
        }

        input[type="submit"]{
            text-align: center;
            display: block;
            margin-left: auto;
            margin-right: auto;
            background-color: white;
            color: #222222;
            border-style: none;
            margin-top: 5%;
            margin-bottom: 5%;
        }

        input[type="submit"]:hover{
            background-color: #fbfbfb;
            color: #222222;
        }
    </style>

<body>
    <div class="container">
        <h1>Login</h1>
        <form action="" method="POST">{% csrf_token %}
            <input type="text" autocomplete="off" placeholder="Username" name="username">
            <input type="password" autocomplete="off" placeholder="Password" name="password">
            <input type="submit" class="btn btn-primary" value="Login">
            {{ form.errors }}
        </form>

        <p style="text-align: center;">Don't have an account ?<span><a href="{% url 'story9:register' %}" style="color: #7d7d7d;" >Sign up</a></span></p>
    </div>  
</body>
</html>

story9/templates/story9/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>

    <style>
        *{
            margin: 0%;
            padding:0%;
            font-family: 'Poppins';
            text-decoration: none;
        }

        .container{
            background-color: #ccbcac;
            width: 30%;
            justify-content: center;
            margin-top : 5%;
            margin-bottom: 5%;
            border-radius: 23px;
            padding: 2%;
        }

        h1{
            text-align: center;
            font-family: Poppins;
            font-style: normal;
            font-weight: bold;
            font-size: 50px;
            line-height: 96px;
            /* identical to box height */

            color: #222222;
        }

        h4{
            justify-content: center;
            text-align: right;
            margin: auto;
            font-size: 22px;
        }

        td{
            width: 50%;
        }

        input[type="text"], input[type="password"]
        {
            width: 100%;
            margin: 0% 0%;
            padding-top: 2%;
            padding-bottom: 2%;
            border-radius: 10px;
            border-style: none;
            outline: none;
            text-align: left;
            padding-left: 3%;
        }

        input[type="submit"]{
            text-align: center;
            display: block;
            margin-left: auto;
            margin-right: auto;
            background-color: white;
            color: #222222;
            border-style: none;
            margin-top: 5%;
            margin-bottom: 5%;
        }

        input[type="submit"]:hover{
            background-color: #fbfbfb;
            color: #222222;
        }
    </style>

<body>
    <div class="container">
        <h1>Sign Up</h1>
        <form action="" method="POST">{% csrf_token %}
            <div class="table-responsive table-borderless justify-content-center">
                <table class="table">
                    <tbody>
                        <tr>
                            <td><h4>Username</h4></td>
                            <td><input type="text" autocomplete="off" name="username" placeholder="Input your username"></td>
                        </tr>
                        <tr>
                            <td><h4>Password</h4></td>
                            <td><input type="password" autocomplete="off" name="password1" placeholder="Input your password"></td>
                        </tr>
                        <tr>
                            <td><h4>Confirm Password</h4></td>
                            <td><input type="password" autocomplete="off" name="password2" placeholder="Confirm your password"></td>
                        </tr>
                    </tbody>
                </table>
                <input type="submit" class="btn btn-primary" autocomplete="off" name="" placeholder="Confirm your password" value="Register">
                {{ form.errors }}
            </div>
        </form>

        <p style="text-align: center;">Already have an account ?  <span><a href="{% url 'story9:login' %}" style="color: #7d7d7d;" >Login</a></span></p>
    </div>  
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hernowo Ari Sutanto</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        {% block head %}
        {% endblock %}
    </head>
    <body>
        <div class="box-top">
            <div class="container">
                <img src="{% static 'images/fotodiri.jpg' %}" class="photo-box" style="display:inline-block;">
                <div class="text-box">
                    <h1>Tentangku...</h1>
                    <p>Halo, nama saya Hernowo Ari Sutanto, biasa dipanggil Hernowo, Nowo, atau Owo.<br>
                        Saya saat ini adalah seorang mahasiswa jurusan Ilmu Komputer di Universitas Indonesia.<br>
                        Hal yang biasa saya lakukan diwaktu luang adalah bermain video game.<br>
                    </p>
                </div>
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:profile'%}">Data diri</a>
                  </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:sekolah'%}">Riwayat sekolah</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:games'%}">Games</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:watchlist'%}">Watchlist</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:story1'%}">Story 1</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:matakuliah'%}">Mata Kuliah</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:forms'%}">Isian Mata Kuliah</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'story7:accordion'%}">Story 7</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'story8:halaman'%}">Story 8</a>
                </li>
              </ul>
              {% if user.is_authenticated %}
              <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" href="#">Halo, {{ user.get_username }}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'story9:logout' %}">LOGOUT</a>
                </li>
              </ul>
              {% else %}

              <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'story9:register' %}">SIGN UP</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'story9:login' %}">LOGIN</a>
                </li>
              </ul>
              {% endif %}
            </div>
          </nav>        
  {% block content %}
  {% endblock content %}
  <div class="box-bot" >
    <h1 class="text-box" style="color: white;"> Kontak </h1>
    <div class="box-kontak">
      <div class="box-logo">
        <a href="https://www.instagram.com/hernowo.arisutanto/" target="_blank">
        <span><img src="{% static 'images/iglogo.png'%}" width="50"></span> hernowo.arisutanto</a>
      </div>
      <div class="box-logo-steam">
        <a href="https://steamcommunity.com/id/BadBadtzMARU" target="_blank">
        <span><img src="{% static 'images/steamlogo.png'%}" width="50"></span> https://steamcommunity.com/id/BadBadtzMARU</a>
      </div>
      <div class="box-logo">
        <a href="https://www.facebook.com/hernowo.arisutanto/" target="_blank">
        <span><img src="{% static 'images/facebook-logo.png'%}" width="35" height="50">  Hernowo Ari Sutanto</span></a>
      </div>
    </div>
  </div>
</body>
</html>